runners:
 local-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest
jobs:   
 hello-world:
  resource_spec: micro
  runner: local-runner
  current_working_directory: ~/
  input: 
   artifact: 
    - id_rsa
  steps:
   - run:
      name: Download python files onto Raspberry Pi
      command: |
       eval `ssh-agent -s`
       chmod 600 ./id_rsa
       ssh-add ./id_rsa
       scp -o "StrictHostKeyChecking=no" ./Adafruit_BMP085.py pi@10.22.109.154:./
       scp -o "StrictHostKeyChecking=no" ./Adafruit_BMP085_example.py pi@10.22.109.154:./
       scp -o "StrictHostKeyChecking=no" ./Adafruit_I2C.py pi@10.22.109.154:./
   - run:
      name: Run python on Raspberry Pi
      command: |
       chmod 777 ./raspberrypi.expect
       ./raspberrypi.expect
      
workflows:
 hello-world-workflow:
  jobs:
   - hello-world
