runners:
 local-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest
jobs:   
 hello-world:
  resource_spec: micro
  runner: local-runner
  current_working_directory: ~/
  steps:
   - run:
      name: Ping Raspberry Pi
      command: |
       chmod 777 ./raspberrypi.expect
       ./raspberrypi.expect
      
workflows:
 hello-world-workflow:
  jobs:
   - hello-world
